# Generated by Django 4.0 on 2024-04-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jakubKrol_zaliczenie', '0002_article_year_alter_article_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Artykuł', 'verbose_name_plural': 'Artykuły'},
        ),
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.PositiveSmallIntegerField(default=2024),
        ),
    ]
