# Generated by Django 4.0 on 2024-04-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jakubKrol_zaliczenie', '0003_alter_article_options_alter_article_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
